---
title: "Biostat M215 Final Project"
author: "Rina Arputhasamy, Andrew Chuang, Carolyn Winskill, Kyle Wu"
date: "2024-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Biostatistics M215: Final Project

## Libraries: 
```{r}
#Relevant libraries:
library(survival)
library(PAmeasures)
library(tidyverse)
library(kableExtra)
library(pec)
data_directory <- "functions/"
source(paste0(data_directory, "pam.survreg.update.R"))
```

## Dataset:
```{r cars}
data(cancer, package = 'survival')
```

## Prediction Accuracy Measures (Rotterdam)

### Cox PH and PAM: 

```{r}
# Fit a multiple Cox PH model with age and edema
fit.coxph <- coxph(Surv(dtime, death) ~ age + meno + size + grade + nodes + pgr + er + hormon + chemo, 
                   data = rotterdam, x=TRUE,y=TRUE)
summary(fit.coxph)
# R.squared and L.squared of Cox PH model
pam.coxph(fit.coxph)
```

### Exponential AFT Model: 

```{r}
fit.exp <- survreg(Surv(dtime, death) ~ age + meno + size + 
                     grade + nodes + pgr + er + hormon + chemo,
                   data = rotterdam, dist="exponential", x=TRUE, y=TRUE)
summary(fit.exp)
# R.squared and L.squared of exponential model
# when data has factors (size), need to pass data directly as shown below
pam.survreg(fit.exp, x.mat = rotterdam)
```

### Lognormal AFT Model: 
```{r}
fit.lognormal <- survreg(Surv(dtime, death) ~ age + meno + size + 
                           grade + nodes + pgr + er + hormon + chemo, 
                   data = rotterdam, dist="lognormal", x=TRUE, y=TRUE)
summary(fit.lognormal)
# R.squared and L.squared of the lognormal model
pam.survreg(fit.lognormal, x.mat = rotterdam)
```

## Prediction Accuracy Measures (SMART Study Data)

```{r}
data(smarto)
```

### Cox PH and PAM: 
```{r}
# Fit a multiple Cox PH model with age and edema
fit.coxph.smart <- coxph(Surv(TEVENT, EVENT) ~ ., 
                   data = smarto, x=TRUE,y=TRUE)
summary(fit.coxph.smart)
# R.squared and L.squared of Cox PH model
pam.coxph(fit.coxph.smart)
```

### Exponential AFT Model (SMART):
```{r}
fit.exp.smarto <- survreg(Surv(TEVENT, EVENT) ~ ., 
                   data = smarto, dist="exponential", x=TRUE, y=TRUE)
summary(fit.exp.smarto)
# R.squared and L.squared of exponential model
pam.survreg(fit.exp.smarto)
```

### Lognormal AFT Model (SMART):
```{r}
fit.lognormal.smarto <- survreg(Surv(TEVENT, EVENT) ~ ., 
                   data = smarto, dist="lognormal", x=TRUE, y=TRUE)
summary(fit.lognormal.smarto)
# R.squared and L.squared of lognormal model
pam.survreg(fit.lognormal.smarto)
```
### Calibration Plot for Cox PH (SMART Data):

```{r}
t <- rotterdam$dtime %>% mean

calPlot(fit.coxph, time=t, data=rotterdam, method = "quantile", q=5,
        bars=TRUE, type="survival", pseudo=FALSE)
```

